[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<*>
  -<sht40_test_main.cpp>

lib_deps =
  knolleary/PubSubClient
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SH110X
  adafruit/Adafruit SHT4X Library

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_flags =
  --timeout=60

[env:sht40_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SHT4X Library
build_src_filter =
  +<sht40_test_main.cpp>